Add ssl support.

diff --git a/etcd-aws-cluster b/etcd-aws-cluster
--- a/etcd-aws-cluster
+++ b/etcd-aws-cluster
@@ -1,11 +1,11 @@
 #! /bin/bash
 pkg="etcd-aws-cluster"
 version="0.5"
-etcd_peers_file_path="/etc/sysconfig/etcd-peers"
+etcd_peers_file_path="/etc/etcd/peers"
 export AWS_DEFAULT_REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq --raw-output .region)
 if [[ ! $AWS_DEFAULT_REGION ]]; then
-    echo "$pkg: failed to get region"
-    exit 1
+  echo "$pkg: failed to get region"
+  exit 1
 fi
 
 # Allow default client/server ports to be changed if necessary
@@ -25,37 +25,37 @@ wait_time=3
 
 #if the script has already run just exit
 if [ -f "$etcd_peers_file_path" ]; then
-    echo "$pkg: etcd-peers file $etcd_peers_file_path already created, exiting"
-    exit 0
+  echo "$pkg: etcd-peers file $etcd_peers_file_path already created, exiting"
+  exit 0
 fi
 
 ec2_instance_id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
 if [[ ! $ec2_instance_id ]]; then
-    echo "$pkg: failed to get instance id from instance metadata"
-    exit 2
+  echo "$pkg: failed to get instance id from instance metadata"
+  exit 2
 fi
 
-ec2_instance_ip=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
-if [[ ! $ec2_instance_ip ]]; then
-    echo "$pkg: failed to get instance IP address"
-    exit 3
+ec2_instance_hostname=$(curl -s http://169.254.169.254/latest/meta-data/local-hostname)
+if [[ ! $ec2_instance_hostname ]]; then
+  echo "$pkg: failed to get instance address"
+  exit 3
 fi
 
 # If we're in proxy mode we don't have to look this up and expect an env var
 if [[ ! $PROXY_ASG ]]; then
-    etcd_proxy=off
-    asg_name=$(aws autoscaling describe-auto-scaling-groups | jq --raw-output ".[] | map(select(.Instances[].InstanceId | contains(\"$ec2_instance_id\"))) | .[].AutoScalingGroupName")
-    if [[ ! "$asg_name" ]]; then
-        echo "$pkg: failed to get the auto scaling group name"
-        exit 4
-    fi
+  etcd_proxy=off
+  asg_name=$(aws autoscaling describe-auto-scaling-groups | jq --raw-output ".[] | map(select(.Instances[].InstanceId | contains(\"$ec2_instance_id\"))) | .[].AutoScalingGroupName")
+  if [[ ! "$asg_name" ]]; then
+    echo "$pkg: failed to get the auto scaling group name"
+    exit 4
+  fi
 else
-    etcd_proxy=on
-    if [[ -n $ASG_BY_TAG ]]; then
-        asg_name=$(aws autoscaling describe-auto-scaling-groups | jq --raw-output ".[] | map(select(.Tags[].Value == \"$PROXY_ASG\")) | .[].AutoScalingGroupName")
-    else
-        asg_name=$PROXY_ASG
-    fi
+  etcd_proxy=on
+  if [[ -n $ASG_BY_TAG ]]; then
+    asg_name=$(aws autoscaling describe-auto-scaling-groups | jq --raw-output ".[] | map(select(.Tags[].Value == \"$PROXY_ASG\")) | .[].AutoScalingGroupName")
+  else
+    asg_name=$PROXY_ASG
+  fi
 fi
 
 etcd_client_scheme=${ETCD_CLIENT_SCHEME:-http}
@@ -64,10 +64,31 @@ echo "client_client_scheme=$etcd_client_scheme"
 etcd_peer_scheme=${ETCD_PEER_SCHEME:-http}
 echo "peer_peer_scheme=$etcd_peer_scheme"
 
-etcd_peer_urls=$(aws ec2 describe-instances --instance-ids $(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name "$asg_name" | jq '.AutoScalingGroups[0].Instances[] | select(.LifecycleState  == "InService") | .InstanceId' | xargs) | jq -r ".Reservations[].Instances | map(\"$etcd_client_scheme://\" + .NetworkInterfaces[].PrivateIpAddress + \":$client_port\")[]")
+# TLS configuration.
+cert_file=${ETCD_CERT_FILE}
+echo "cert_file=$cert_file"
+
+ca_file=${ETCD_CA_FILE}
+echo "ca_file=$ca_file"
+
+key_file=${ETCD_KEY_FILE}
+echo "key_file=$key_file"
+
+if [ "$etcd_client_scheme" = "https" ]; then
+  ETCD_CURLOPTS="$ETCD_CURLOPTS --cert $cert_file --key $key_file --cacert $ca_file"
+fi
+
+# Configure advertise and client urls.
+etcd_initial_advertise_peer_urls="$etcd_peer_scheme://${ec2_instance_hostname}:2380"
+echo "etcd_initial_advertise_peer_urls=$etcd_initial_advertise_peer_urls"
+
+etcd_advertise_client_urls="$etcd_client_scheme://${ec2_instance_hostname}:2379"
+echo "etcd_advertise_client_urls=$etcd_advertise_client_urls"
+
+etcd_peer_urls=$(aws ec2 describe-instances --instance-ids $(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name "$asg_name" | jq '.AutoScalingGroups[0].Instances[] | select(.LifecycleState  == "InService") | .InstanceId' | xargs) | jq -r ".Reservations[].Instances | map(\"$etcd_client_scheme://\" + .NetworkInterfaces[].PrivateDnsName + \":$client_port\")[]")
 if [[ ! $etcd_peer_urls ]]; then
-    echo "$pkg: unable to find members of auto scaling group"
-    exit 5
+  echo "$pkg: unable to find members of auto scaling group"
+  exit 5
 fi
 
 echo "etcd_peer_urls=$etcd_peer_urls"
@@ -77,20 +98,20 @@ etcd_existing_peer_names=
 etcd_good_member_url=
 
 for url in $etcd_peer_urls; do
-    case "$url" in
-        # If we're in proxy mode this is an error, but unlikely to happen?
-        *$ec2_instance_ip*) continue;;
-    esac
+  case "$url" in
+    # If we're in proxy mode this is an error, but unlikely to happen?
+    *$ec2_instance_hostname*) continue;;
+  esac
 
-    etcd_members=$(curl $ETCD_CURLOPTS -f -s $url/v2/members)
+  etcd_members=$(curl $ETCD_CURLOPTS -f -s $url/v2/members)
 
-    if [[ $? == 0 && $etcd_members ]]; then
-        etcd_good_member_url="$url"
-		echo "etcd_members=$etcd_members"
-        etcd_existing_peer_urls=$(echo "$etcd_members" | jq --raw-output .[][].peerURLs[0])
-		etcd_existing_peer_names=$(echo "$etcd_members" | jq --raw-output .[][].name)
-	break
-    fi
+  if [[ $? == 0 && $etcd_members ]]; then
+    etcd_good_member_url="$url"
+    echo "etcd_members=$etcd_members"
+    etcd_existing_peer_urls=$(echo "$etcd_members" | jq --raw-output .[][].peerURLs[0])
+    etcd_existing_peer_names=$(echo "$etcd_members" | jq --raw-output .[][].name)
+    break
+  fi
 done
 
 echo "etcd_good_member_url=$etcd_good_member_url"
@@ -100,94 +121,104 @@ echo "etcd_existing_peer_names=$etcd_existing_peer_names"
 # if I am not listed as a member of the cluster assume that this is a existing cluster
 # this will also be the case for a proxy situation
 if [[ $etcd_existing_peer_urls && $etcd_existing_peer_names != *"$ec2_instance_id"* ]]; then
-    echo "joining existing cluster"
+  echo "joining existing cluster"
 
-    # eject bad members from cluster
-    peer_regexp=$(echo "$etcd_peer_urls" | sed 's/^.*https\{0,1\}:\/\/\([0-9.]*\):[0-9]*.*$/contains(\\"\/\/\1:\\")/' | xargs | sed 's/  */ or /g')
-    if [[ ! $peer_regexp ]]; then
-        echo "$pkg: failed to create peer regular expression"
-        exit 6
+  # eject bad members from cluster
+  peer_regexp=$(echo "$etcd_peer_urls" | sed 's/^.*https\{0,1\}:\/\/\([0-9.]*\):[0-9]*.*$/contains(\\"\/\/\1:\\")/' | xargs | sed 's/  */ or /g')
+  if [[ ! $peer_regexp ]]; then
+    echo "$pkg: failed to create peer regular expression"
+    exit 6
+  fi
+
+  echo "peer_regexp=$peer_regexp"
+  bad_peer=$(echo "$etcd_members" | jq --raw-output ".[] | map(select(.peerURLs[] | $peer_regexp | not )) | .[].id")
+  echo "bad_peer=$bad_peer"
+
+  if [[ $bad_peer ]]; then
+    for bp in $bad_peer; do
+      status=0
+      retry=1
+      until [[ $status = $delete_ok || $status =  $delete_gone || $retry = $retry_times ]]; do
+        status=$(curl $ETCD_CURLOPTS -f -s -w %{http_code} "$etcd_good_member_url/v2/members/$bp" -XDELETE)
+        echo "$pkg: removing bad peer $bp, retry $((retry++)), return code $status."
+        sleep $wait_time
+      done
+      if [[ $status != $delete_ok && $status != $delete_gone ]]; then
+        echo "$pkg: ERROR: failed to remove bad peer: $bad_peer, return code $status."
+        exit 7
+      else
+        echo "$pkg: removed bad peer: $bad_peer, return code $status."
+      fi
+    done
+  fi
+
+  # If we're not a proxy we add ourselves as a member to the cluster
+  if [[ ! $PROXY_ASG ]]; then
+    peer_url="$etcd_peer_scheme://$ec2_instance_hostname:$server_port"
+    etcd_initial_cluster=$(curl $ETCD_CURLOPTS -s -f "$etcd_good_member_url/v2/members" | jq --raw-output '.[] | map(.name + "=" + .peerURLs[0]) | .[]' | xargs | sed 's/  */,/g')$(echo ",$ec2_instance_id=$peer_url")
+    echo "etcd_initial_cluster=$etcd_initial_cluster"
+    if [[ ! $etcd_initial_cluster ]]; then
+      echo "$pkg: docker command to get etcd peers failed"
+      exit 8
     fi
 
-    echo "peer_regexp=$peer_regexp"
-    bad_peer=$(echo "$etcd_members" | jq --raw-output ".[] | map(select(.peerURLs[] | $peer_regexp | not )) | .[].id")
-    echo "bad_peer=$bad_peer"
-
-    if [[ $bad_peer ]]; then
-        for bp in $bad_peer; do
-            status=0
-            retry=1
-            until [[ $status = $delete_ok || $status =  $delete_gone || $retry = $retry_times ]]; do
-                status=$(curl $ETCD_CURLOPTS -f -s -w %{http_code} "$etcd_good_member_url/v2/members/$bp" -XDELETE)
-                echo "$pkg: removing bad peer $bp, retry $((retry++)), return code $status."
-                sleep $wait_time
-            done
-            if [[ $status != $delete_ok && $status != $delete_gone ]]; then
-                echo "$pkg: ERROR: failed to remove bad peer: $bad_peer, return code $status."
-                exit 7
-            else
-                echo "$pkg: removed bad peer: $bad_peer, return code $status."
-            fi
-        done
-    fi
-
-    # If we're not a proxy we add ourselves as a member to the cluster
-    if [[ ! $PROXY_ASG ]]; then
-        peer_url="$etcd_peer_scheme://$ec2_instance_ip:$server_port"
-        etcd_initial_cluster=$(curl $ETCD_CURLOPTS -s -f "$etcd_good_member_url/v2/members" | jq --raw-output '.[] | map(.name + "=" + .peerURLs[0]) | .[]' | xargs | sed 's/  */,/g')$(echo ",$ec2_instance_id=$peer_url")
-        echo "etcd_initial_cluster=$etcd_initial_cluster"
-        if [[ ! $etcd_initial_cluster ]]; then
-            echo "$pkg: docker command to get etcd peers failed"
-            exit 8
-        fi
-
-        # join an existing cluster
-        status=0
-        retry=1
-        until [[ $status = $add_ok || $status = $already_added || $retry = $retry_times ]]; do
-            status=$(curl $ETCD_CURLOPTS -f -s -w %{http_code} -o /dev/null -XPOST "$etcd_good_member_url/v2/members" -H "Content-Type: application/json" -d "{\"peerURLs\": [\"$peer_url\"], \"name\": \"$ec2_instance_id\"}")
-            echo "$pkg: adding instance ID $ec2_instance_id with peer URL $peer_url, retry $((retry++)), return code $status."
-            sleep $wait_time
-        done
-        if [[ $status != $add_ok && $status != $already_added ]]; then
-            echo "$pkg: unable to add $peer_url to the cluster: return code $status."
-            exit 9
-        else
-            echo "$pkg: added $peer_url to existing cluster, return code $status"
-        fi
-    # If we are a proxy we just want the list for the actual cluster
+    # join an existing cluster
+    status=0
+    retry=1
+    until [[ $status = $add_ok || $status = $already_added || $retry = $retry_times ]]; do
+      status=$(curl $ETCD_CURLOPTS -f -s -w %{http_code} -o /dev/null -XPOST "$etcd_good_member_url/v2/members" -H "Content-Type: application/json" -d "{\"peerURLs\": [\"$peer_url\"], \"name\": \"$ec2_instance_id\"}")
+      echo "$pkg: adding instance ID $ec2_instance_id with peer URL $peer_url, retry $((retry++)), return code $status."
+      sleep $wait_time
+    done
+    if [[ $status != $add_ok && $status != $already_added ]]; then
+      echo "$pkg: unable to add $peer_url to the cluster: return code $status."
+      exit 9
     else
-        etcd_initial_cluster=$(curl $ETCD_CURLOPTS -s -f "$etcd_good_member_url/v2/members" | jq --raw-output '.[] | map(.name + "=" + .peerURLs[0]) | .[]' | xargs | sed 's/  */,/g')
-        echo "etcd_initial_cluster=$etcd_initial_cluster"
-        if [[ ! $etcd_initial_cluster ]]; then
-            echo "$pkg: docker command to get etcd peers failed"
-            exit 8
-        fi
+      echo "$pkg: added $peer_url to existing cluster, return code $status"
     fi
+  # If we are a proxy we just want the list for the actual cluster
+  else
+    etcd_initial_cluster=$(curl $ETCD_CURLOPTS -s -f "$etcd_good_member_url/v2/members" | jq --raw-output '.[] | map(.name + "=" + .peerURLs[0]) | .[]' | xargs | sed 's/  */,/g')
+    echo "etcd_initial_cluster=$etcd_initial_cluster"
+    if [[ ! $etcd_initial_cluster ]]; then
+      echo "$pkg: docker command to get etcd peers failed"
+      exit 8
+    fi
+  fi
 
-    cat > "$etcd_peers_file_path" <<EOF
+  echo "etcd_initial_cluster_state=existing"
+
+  cat > "$etcd_peers_file_path" <<EOF
 ETCD_INITIAL_CLUSTER_STATE=existing
 ETCD_NAME=$ec2_instance_id
 ETCD_INITIAL_CLUSTER="$etcd_initial_cluster"
 ETCD_PROXY=$etcd_proxy
+ETCD_LISTEN_CLIENT_URLS=${etcd_client_scheme}://0.0.0.0:2379
+ETCD_LISTEN_PEER_URLS=${etcd_peer_scheme}://0.0.0.0:2380
+ETCD_INITIAL_ADVERTISE_PEER_URLS=$etcd_initial_advertise_peer_urls
+ETCD_ADVERTISE_CLIENT_URLS=$etcd_advertise_client_urls
 EOF
 
 # otherwise I was already listed as a member so assume that this is a new cluster
 else
-    # create a new cluster
-    echo "creating new cluster"
+  # create a new cluster
+  echo "etcd_initial_cluster_state=new"
 
-    etcd_initial_cluster=$(aws ec2 describe-instances --instance-ids $(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name "$asg_name" | jq .AutoScalingGroups[0].Instances[].InstanceId | xargs) | jq -r ".Reservations[].Instances | map(.InstanceId + \"=$etcd_peer_scheme://\" + .NetworkInterfaces[].PrivateIpAddress + \":$server_port\")[]" | xargs | sed 's/  */,/g')
-    echo "etcd_initial_cluster=$etcd_initial_cluster"
-    if [[ ! $etcd_initial_cluster ]]; then
-        echo "$pkg: unable to get peers from auto scaling group"
-        exit 10
-    fi
+  etcd_initial_cluster=$(aws ec2 describe-instances --instance-ids $(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name "$asg_name" | jq .AutoScalingGroups[0].Instances[].InstanceId | xargs) | jq -r ".Reservations[].Instances | map(.InstanceId + \"=$etcd_peer_scheme://\" + .NetworkInterfaces[].PrivateDnsName + \":$server_port\")[]" | xargs | sed 's/  */,/g')
+  echo "etcd_initial_cluster=$etcd_initial_cluster"
+  if [[ ! $etcd_initial_cluster ]]; then
+    echo "$pkg: unable to get peers from auto scaling group"
+    exit 10
+  fi
 
     cat > "$etcd_peers_file_path" <<EOF
 ETCD_INITIAL_CLUSTER_STATE=new
 ETCD_NAME=$ec2_instance_id
 ETCD_INITIAL_CLUSTER="$etcd_initial_cluster"
+ETCD_LISTEN_CLIENT_URLS=${etcd_client_scheme}://0.0.0.0:2379
+ETCD_LISTEN_PEER_URLS=${etcd_peer_scheme}://0.0.0.0:2380
+ETCD_INITIAL_ADVERTISE_PEER_URLS=$etcd_initial_advertise_peer_urls
+ETCD_ADVERTISE_CLIENT_URLS=$etcd_advertise_client_urls
 EOF
 fi
 
